Traceback (most recent call last):
  File "/home/ricardo/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/lib/python3/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%pylab inline
matplotlib.rcParams['mathtext.fontset'] = 'cm'
#k2 = np.array([2.96, 2.911, 2.863, 2.843, 2.823])
#k = np.array([3.856, 3.804, 3.752, 3.732, 3.710])
k = np.array([3.331, 3.281, 3.231, 3.210, 3.19])
nu = np.array([1./2., 1./3., 1./6., 1./10., 1./30.])
plt.semilogx(nu,(k/(a0*4.0*a0))/ks,'ko:',fillstyle='none')
#plt.semilogx(nu,(k2/(a0*4.0*a0))/ks,'bo:',fillstyle='none')
plt.semilogx(nu,k2*0+1,'k--',fillstyle='none')
plt.ylabel('$k/k^{*}$', color='k', horizontalalignment='right',rotation=0, fontsize=20)
plt.xlabel('$\\nu$', fontsize=20)
plt.legend(['$LBPM$'],fontsize=11.,bbox_to_anchor=(1.0, 1.02))
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_8740/1386871811.py[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0mplt[0m[0;34m.[0m[0msemilogx[0m[0;34m([0m[0mnu[0m[0;34m,[0m[0;34m([0m[0mk[0m[0;34m/[0m[0;34m([0m[0ma0[0m[0;34m*[0m[0;36m4.0[0m[0;34m*[0m[0ma0[0m[0;34m)[0m[0;34m)[0m[0;34m/[0m[0mks[0m[0;34m,[0m[0;34m'ko:'[0m[0;34m,[0m[0mfillstyle[0m[0;34m=[0m[0;34m'none'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;31m#plt.semilogx(nu,(k2/(a0*4.0*a0))/ks,'bo:',fillstyle='none')[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m [0mplt[0m[0;34m.[0m[0msemilogx[0m[0;34m([0m[0mnu[0m[0;34m,[0m[0mk2[0m[0;34m*[0m[0;36m0[0m[0;34m+[0m[0;36m1[0m[0;34m,[0m[0;34m'k--'[0m[0;34m,[0m[0mfillstyle[0m[0;34m=[0m[0;34m'none'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0mplt[0m[0;34m.[0m[0mylabel[0m[0;34m([0m[0;34m'$k/k^{*}$'[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m'k'[0m[0;34m,[0m [0mhorizontalalignment[0m[0;34m=[0m[0;34m'right'[0m[0;34m,[0m[0mrotation[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0mfontsize[0m[0;34m=[0m[0;36m20[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0mplt[0m[0;34m.[0m[0mxlabel[0m[0;34m([0m[0;34m'$\\nu$'[0m[0;34m,[0m [0mfontsize[0m[0;34m=[0m[0;36m20[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'k2' is not defined
NameError: name 'k2' is not defined

